name: 'Build, Push and Deploy to Heroku and Testing'
on:
    push:
        branches: 
            - main
jobs:
  back-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug directory content
        run: ls -R

      - name: Deploy Docker Image to Heroku App
        uses: jctaveras/heroku-deploy@v3.1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }} 
          api_key: ${{ secrets.HEROKU_API_KEY }} 
          app_name: ${{ secrets.HEROKU_BACK_APP_NAME }} 
          dockerfile_path: ./backend
          process_type: 'web' 
 
  front-build:
    needs: back-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Docker Image to Heroku App
        uses: jctaveras/heroku-deploy@v3.1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }} 
          api_key: ${{ secrets.HEROKU_API_KEY }} 
          app_name: ${{ secrets.HEROKU_FRONT_APP_NAME }} 
          dockerfile_path: ./frontend
          process_type: 'web' 


      