name: 'Deploy'
on:
    push:
        branches: 
            - main
jobs:
  back-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug directory content
        run: ls -R

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} 
          heroku_app_name: ${{ secrets.HEROKU_BACK_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: "./backend"
 
  front-build:
    needs: back-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} 
          heroku_app_name: ${{ secrets.HEROKU_FRONT_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          appdir: "./frontend"


      