name: 'Build, Push and Deploy to Heroku and Testing'
on:
    push:
        branches: 
            - main
jobs:
  back-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Deploy to Heroku
        uses: jctaveras/heroku-deploy@v1.0.0 
        with:
          email: ${{ secrets.HEROKU_EMAIL }} 
          api_key: ${{ secrets.HEROKU_API_KEY }} 
          app_name: ${{ secrets.HEROKU_BACK_APP_NAME }} 
          dockerfile_path: '../../backend'
          process_type: 'web' 

  front-build:
    needs: python-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Deploy to Heroku
        uses: jctaveras/heroku-deploy@v1.0.0 
        with:
          email: ${{ secrets.HEROKU_EMAIL }} 
          api_key: ${{ secrets.HEROKU_API_KEY }} 
          app_name: ${{ secrets.HEROKU_FRONT_APP_NAME }} 
          dockerfile_path: '../../frontend'
          process_type: 'web' 